/**
 * CSS Tokens Exporter
 *
 * Pure function: BrandKit → CSS custom properties string.
 * Deterministic. No AI. No side effects.
 *
 * Output uses `--brand-` prefix to avoid collisions with
 * framework-specific variables.
 */

import type { BrandKit } from '../schema/brand-kit.js';

export function exportCssTokens(kit: BrandKit): string {
  const lines: string[] = [];

  lines.push('/**');
  lines.push(` * ${kit.identity.name} — Design Tokens`);
  lines.push(` * Generated by brand-forge v${kit.meta.version}`);
  lines.push(` * Last updated: ${kit.meta.updated}`);
  lines.push(' * DO NOT EDIT — regenerate with: brand-forge export css');
  lines.push(' */');
  lines.push('');
  lines.push(':root {');

  // --- Colors ---
  lines.push('  /* Colors — Primary */');
  lines.push(`  --brand-primary: ${kit.colors.primary.hex};`);
  lines.push(`  --brand-secondary: ${kit.colors.secondary.hex};`);
  lines.push(`  --brand-accent: ${kit.colors.accent.hex};`);
  lines.push('');

  lines.push('  /* Colors — Neutral Scale */');
  for (const [step, hex] of Object.entries(kit.colors.neutral)) {
    lines.push(`  --brand-neutral-${step}: ${hex};`);
  }
  lines.push('');

  lines.push('  /* Colors — Semantic */');
  lines.push(`  --brand-success: ${kit.colors.semantic.success.hex};`);
  lines.push(`  --brand-warning: ${kit.colors.semantic.warning.hex};`);
  lines.push(`  --brand-error: ${kit.colors.semantic.error.hex};`);
  lines.push(`  --brand-info: ${kit.colors.semantic.info.hex};`);
  lines.push('');

  lines.push('  /* Colors — Surfaces */');
  for (const [name, hex] of Object.entries(kit.colors.surfaces)) {
    const kebab = name.replace(/([A-Z])/g, '-$1').toLowerCase();
    lines.push(`  --brand-${kebab}: ${hex};`);
  }
  lines.push('');

  // --- Typography ---
  lines.push('  /* Typography */');
  const { display, body, mono } = kit.typography;
  lines.push(`  ${display.cssVariable || '--brand-font-display'}: '${display.family}', ${display.fallbacks.join(', ')};`);
  lines.push(`  ${body.cssVariable || '--brand-font-body'}: '${body.family}', ${body.fallbacks.join(', ')};`);
  lines.push(`  ${mono.cssVariable || '--brand-font-mono'}: '${mono.family}', ${mono.fallbacks.join(', ')};`);
  lines.push('');

  lines.push('  /* Type Scale */');
  for (const step of kit.typography.scale.steps) {
    lines.push(`  --brand-text-${step.name}: ${step.sizeRem}rem;`);
    if (step.sizeMobileRem) {
      lines.push(`  --brand-text-${step.name}-mobile: ${step.sizeMobileRem}rem;`);
    }
    lines.push(`  --brand-leading-${step.name}: ${step.lineHeight};`);
  }
  lines.push('');

  // --- Spacing ---
  lines.push('  /* Spacing */');
  for (const [step, rem] of Object.entries(kit.spacing)) {
    lines.push(`  --brand-space-${step}: ${rem}rem;`);
  }
  lines.push('');

  // --- Border Radius ---
  lines.push('  /* Border Radius */');
  for (const [name, rem] of Object.entries(kit.radius)) {
    if (name === 'full') {
      lines.push(`  --brand-radius-full: 9999px;`);
    } else if (name === 'none') {
      lines.push(`  --brand-radius-none: 0;`);
    } else {
      lines.push(`  --brand-radius-${name}: ${rem}rem;`);
    }
  }
  lines.push('');

  // --- Layout ---
  lines.push('  /* Layout */');
  lines.push(`  --brand-max-width: ${kit.layout.maxContentWidth}rem;`);
  for (const [name, px] of Object.entries(kit.layout.breakpoints)) {
    lines.push(`  --brand-bp-${name}: ${px}px;`);
  }

  lines.push('}');

  return lines.join('\n');
}
