/**
 * DESIGN.md Exporter
 *
 * Pure function: BrandKit → DESIGN.md string (YAML frontmatter + Markdown body).
 * Follows the google-labs/design.md specification: machine-readable tokens in
 * the frontmatter, human rationale in canonical markdown sections.
 *
 * Deterministic. No AI. No network. No Date.now().
 */

import type { BrandKit } from '../schema/brand-kit.js';

// ---------------------------------------------------------------------------
// YAML emit helpers — hand-serialized for determinism and zero new deps.
// The brand-kit shape is known and controlled, so we can emit a narrow subset
// of YAML 1.2 safely.
// ---------------------------------------------------------------------------

const INDENT = '  ';

function indent(depth: number): string {
  return INDENT.repeat(depth);
}

function yamlKey(key: string): string {
  // Numeric-looking keys ("50", "2xl") must be quoted to stay string keys.
  return /^[A-Za-z_][A-Za-z0-9_-]*$/.test(key) && !/^\d/.test(key) ? key : `"${key}"`;
}

function yamlScalar(value: string | number | boolean): string {
  if (typeof value === 'boolean' || typeof value === 'number') return String(value);
  // Quote hex colors, values with special chars, or empty strings.
  if (value === '' || /[:#{}\[\],&*!|>'"%@`]|^[-?]|^\s|\s$/.test(value)) {
    return `"${value.replace(/"/g, '\\"')}"`;
  }
  return value;
}

function yamlInlineList(items: Array<string | number>): string {
  return `[${items.map((v) => yamlScalar(v)).join(', ')}]`;
}

// ---------------------------------------------------------------------------
// Frontmatter builder
// ---------------------------------------------------------------------------

function buildFrontmatter(kit: BrandKit): string[] {
  const lines: string[] = [];
  lines.push('---');
  lines.push(`# Generated by brand-forge v${kit.meta.version} — DO NOT EDIT`);
  lines.push('# Regenerate with: brand-forge export design-md');
  lines.push(`schemaVersion: ${kit.meta.schemaVersion}`);
  lines.push(`name: ${yamlScalar(kit.identity.name)}`);
  if (kit.identity.tagline) lines.push(`tagline: ${yamlScalar(kit.identity.tagline)}`);
  if (kit.identity.domain) lines.push(`domain: ${yamlScalar(kit.identity.domain)}`);
  lines.push(`mode: ${kit.defaultMode}`);
  lines.push('');

  // --- colors ---
  lines.push('colors:');
  lines.push(`${indent(1)}primary: ${yamlScalar(kit.colors.primary.hex)}`);
  lines.push(`${indent(1)}secondary: ${yamlScalar(kit.colors.secondary.hex)}`);
  lines.push(`${indent(1)}accent: ${yamlScalar(kit.colors.accent.hex)}`);
  lines.push(`${indent(1)}neutral:`);
  for (const [step, hex] of Object.entries(kit.colors.neutral)) {
    lines.push(`${indent(2)}${yamlKey(step)}: ${yamlScalar(hex)}`);
  }
  lines.push(`${indent(1)}semantic:`);
  for (const [role, token] of Object.entries(kit.colors.semantic)) {
    lines.push(`${indent(2)}${role}: ${yamlScalar(token.hex)}`);
  }
  lines.push(`${indent(1)}surfaces:`);
  for (const [name, hex] of Object.entries(kit.colors.surfaces)) {
    lines.push(`${indent(2)}${name}: ${yamlScalar(hex)}`);
  }

  // Flat aliases for every nested color, emitted alongside the grouped blocks.
  //
  // Why: conformance readers that check a rendered page against this file walk
  // only the top level of `colors:` for string values — impeccable's
  // cli/engine/design-system.mjs addColorObject() is non-recursive. Without
  // these aliases such a reader sees primary/secondary/accent and treats every
  // neutral, semantic, and surface color as undeclared drift, which on a real
  // page is almost entirely false positives (verified 2026-07-26: 8 findings
  // against a flickday page, 6 of them declared colors; adding the aliases took
  // it to 2, both genuine).
  //
  // The design.md spec permits additional top-level keys, so the grouped blocks
  // above stay canonical and these are purely additive. Keys are prefixed to
  // avoid colliding with primary/secondary/accent.
  for (const [step, hex] of Object.entries(kit.colors.neutral)) {
    lines.push(`${indent(1)}neutral-${step}: ${yamlScalar(hex)}`);
  }
  for (const [role, token] of Object.entries(kit.colors.semantic)) {
    lines.push(`${indent(1)}semantic-${role}: ${yamlScalar(token.hex)}`);
  }
  for (const [name, hex] of Object.entries(kit.colors.surfaces)) {
    lines.push(`${indent(1)}surface-${name}: ${yamlScalar(hex)}`);
  }
  lines.push('');

  // --- typography ---
  const fonts = [
    ['display', kit.typography.display],
    ['body', kit.typography.body],
    ['mono', kit.typography.mono],
  ] as const;

  lines.push('typography:');
  lines.push(`${indent(1)}fonts:`);
  for (const [role, font] of fonts) {
    lines.push(`${indent(2)}${role}:`);
    lines.push(`${indent(3)}family: ${yamlScalar(font.family)}`);
    lines.push(`${indent(3)}fallbacks: ${yamlInlineList(font.fallbacks)}`);
    lines.push(`${indent(3)}weights: ${yamlInlineList(font.weights)}`);
    if (font.letterSpacing !== undefined && font.letterSpacing !== 0) {
      lines.push(`${indent(3)}letterSpacing: ${yamlScalar(`${font.letterSpacing}em`)}`);
    }
    if (font.textTransform && font.textTransform !== 'none') {
      lines.push(`${indent(3)}textTransform: ${yamlScalar(font.textTransform)}`);
    }
  }
  lines.push(`${indent(1)}scale:`);
  for (const step of kit.typography.scale.steps) {
    lines.push(`${indent(2)}${yamlKey(step.name)}:`);
    lines.push(`${indent(3)}size: ${yamlScalar(`${step.sizeRem}rem`)}`);
    if (step.sizeMobileRem !== undefined) {
      lines.push(`${indent(3)}sizeMobile: ${yamlScalar(`${step.sizeMobileRem}rem`)}`);
    }
    lines.push(`${indent(3)}lineHeight: ${step.lineHeight}`);
    lines.push(`${indent(3)}weight: ${step.weight}`);
    lines.push(`${indent(3)}font: ${step.font}`);
  }

  // Role and step aliases, for the same reason as the flat colors above and
  // against the same reader.
  //
  // impeccable's addTypographyFonts (cli/engine/design-system.mjs) walks the top
  // level of `typography:` for a role object carrying a string `fontFamily`;
  // addTypographySizes wants either a flat name -> size string under `scale:` or
  // a role object carrying `fontSize`. This exporter emits `fonts.<role>.family`
  // and `scale.<name>.size` — wrong nesting and wrong key on both paths — so
  // both walks find nothing. Measured 2026-07-26: a generated DESIGN.md parsed
  // to 19 colors, ZERO fonts and zero type steps.
  //
  // That failure is worse than it sounds. Declaring no fonts does not relax the
  // font check; it makes every font on the rendered page undeclared, so the
  // check either floods or is switched off — and a switched-off check reads as
  // a passing one.
  //
  // Additive, like the colors: the grouped blocks above stay canonical. Step
  // aliases are prefixed because a scale step may legitimately be named
  // `display`, which would collide with the display font role.
  for (const [role, font] of fonts) {
    lines.push(`${indent(1)}${role}:`);
    lines.push(
      `${indent(2)}fontFamily: ${yamlScalar([font.family, ...font.fallbacks].join(', '))}`,
    );
  }
  for (const step of kit.typography.scale.steps) {
    lines.push(`${indent(1)}${yamlKey(`step-${step.name}`)}:`);
    lines.push(`${indent(2)}fontSize: ${yamlScalar(`${step.sizeRem}rem`)}`);
  }
  lines.push('');

  // --- spacing ---
  lines.push('spacing:');
  for (const [step, rem] of Object.entries(kit.spacing)) {
    lines.push(`${indent(1)}${yamlKey(step)}: ${yamlScalar(`${rem}rem`)}`);
  }
  lines.push('');

  // --- rounded ---
  lines.push('rounded:');
  for (const [name, value] of Object.entries(kit.radius)) {
    const emitted =
      value === 0 ? '0' : value >= 100 ? `${value}px` : `${value}rem`;
    lines.push(`${indent(1)}${yamlKey(name)}: ${yamlScalar(emitted)}`);
  }
  lines.push('');

  // --- layout ---
  lines.push('layout:');
  lines.push(`${indent(1)}maxContentWidth: ${yamlScalar(`${kit.layout.maxContentWidth}rem`)}`);
  lines.push(`${indent(1)}breakpoints:`);
  for (const [name, px] of Object.entries(kit.layout.breakpoints)) {
    lines.push(`${indent(2)}${yamlKey(name)}: ${yamlScalar(`${px}px`)}`);
  }
  lines.push(`${indent(1)}sectionPadding: ${yamlScalar(`{spacing.${kit.layout.sectionPadding}}`)}`);
  lines.push(`${indent(1)}containerPadding: ${yamlScalar(`{spacing.${kit.layout.containerPadding}}`)}`);
  lines.push('---');
  lines.push('');

  return lines;
}

// ---------------------------------------------------------------------------
// Body builder — canonical section order per google-labs/design.md:
// Overview → Colors → Typography → Layout → Shapes → Voice → Do's and Don'ts
// ---------------------------------------------------------------------------

function buildBody(kit: BrandKit): string[] {
  const lines: string[] = [];
  const { identity, colors, typography, voice } = kit;

  lines.push(`# ${identity.name} Design System`);
  lines.push('');

  // --- Overview ---
  lines.push('## Overview');
  lines.push('');
  if (identity.tagline) lines.push(`**Tagline:** ${identity.tagline}`);
  if (identity.mission) lines.push(`**Mission:** ${identity.mission}`);
  if (identity.positioning) lines.push(`**Positioning:** ${identity.positioning}`);
  if (identity.audience.length) lines.push(`**Audience:** ${identity.audience.join(', ')}`);
  if (identity.personality.length) lines.push(`**Personality:** ${identity.personality.join(', ')}`);
  lines.push('');

  // --- Colors ---
  lines.push('## Colors');
  lines.push('');
  lines.push('### Primary');
  lines.push(`- **{colors.primary}** — ${colors.primary.name}. ${colors.primary.usage || 'Primary accent.'}`);
  lines.push(`- **{colors.secondary}** — ${colors.secondary.name}. ${colors.secondary.usage || 'Secondary accent.'}`);
  lines.push(`- **{colors.accent}** — ${colors.accent.name}. ${colors.accent.usage || 'Accent.'}`);
  lines.push('');

  lines.push('### Semantic');
  for (const [role, token] of Object.entries(colors.semantic)) {
    lines.push(`- **{colors.semantic.${role}}** — ${token.name}. ${token.usage || role}.`);
  }
  lines.push('');

  lines.push('### Neutral Scale');
  lines.push('The neutral ramp carries surface, border, and text hierarchy. Components must reference scale steps (`{colors.neutral.200}`) rather than raw hex values.');
  lines.push('');

  // --- Typography ---
  lines.push('## Typography');
  lines.push('');
  lines.push(`**Display** — ${typography.display.family}. Used for display steps and headings 1–3.`);
  if (typography.display.textTransform && typography.display.textTransform !== 'none') {
    const ls = typography.display.letterSpacing ?? 0;
    lines.push(`Applied with \`text-transform: ${typography.display.textTransform}\`${ls !== 0 ? ` and \`letter-spacing: ${ls}em\`` : ''}.`);
  }
  lines.push('');
  lines.push(`**Body** — ${typography.body.family}. Used for body copy, small text, and UI labels.`);
  lines.push('');
  lines.push(`**Mono** — ${typography.mono.family}. Used for code and overline labels.`);
  lines.push('');
  lines.push('### Scale');
  lines.push(`Major-second ratio on a ${typography.scale.baseSizePx}px base. Each step declares both a desktop and mobile size; consumers must apply the mobile size below the \`md\` breakpoint.`);
  lines.push('');

  // --- Layout ---
  lines.push('## Layout');
  lines.push('');
  lines.push(`Content width tops out at {layout.maxContentWidth}. Section padding uses \`{spacing.${kit.layout.sectionPadding}}\`; container gutters use \`{spacing.${kit.layout.containerPadding}}\`.`);
  lines.push('');
  lines.push('Breakpoints follow Tailwind defaults and are declared in frontmatter under `layout.breakpoints`.');
  lines.push('');

  // --- Shapes ---
  lines.push('## Shapes');
  lines.push('');
  lines.push('Border radius scales from `{rounded.sm}` (inputs, chips) through `{rounded.lg}` (cards) to `{rounded.full}` (avatars, pills). Components must select a scale step; raw radius values in component CSS are a linting violation.');
  lines.push('');

  // --- Voice ---
  if (voice.attributes.length || voice.antiPatterns.length || voice.examples.length) {
    lines.push('## Voice');
    lines.push('');
    if (voice.attributes.length) {
      lines.push('### Attributes');
      for (const attr of voice.attributes) {
        lines.push(`- **${attr.trait}** — ${attr.description}`);
        if (attr.example) lines.push(`  > "${attr.example}"`);
      }
      lines.push('');
    }
    if (voice.antiPatterns.length) {
      lines.push('### Avoid');
      for (const ap of voice.antiPatterns) {
        const patterns = ap.patterns.slice(0, 6).join(', ');
        const ellipsis = ap.patterns.length > 6 ? '…' : '';
        lines.push(`- **${ap.category}** (${ap.severity}): ${patterns}${ellipsis}`);
        if (ap.suggestion) lines.push(`  > Instead: ${ap.suggestion}`);
      }
      lines.push('');
    }
  }

  // --- Do's and Don'ts ---
  lines.push(`## Do's and Don'ts`);
  lines.push('');
  lines.push('**Do**');
  lines.push('- Reference tokens by path (`{colors.primary}`, `{spacing.6}`) rather than raw values in components.');
  lines.push('- Reserve `{colors.primary}` for the single primary action per viewport.');
  lines.push('- Prefer surface tokens (`{colors.surfaces.card}`) over raw neutrals for component backgrounds.');
  if (typography.display.textTransform && typography.display.textTransform !== 'none') {
    lines.push(`- Apply the \`${typography.display.textTransform}\` rule to display type only — never to body copy.`);
  }
  lines.push('');
  lines.push(`**Don't**`);
  lines.push('- Hard-code hex values, raw rem/px spacing, or font families in component CSS.');
  lines.push('- Stack competing CTAs using `{colors.primary}` and `{colors.accent}` in the same viewport.');
  lines.push('- Use `{typography.fonts.mono}` for body copy or headings.');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push(`*Generated by brand-forge v${kit.meta.version} from \`brand-kit.json\` (schema v${kit.meta.schemaVersion}, updated ${kit.meta.updated}).*`);

  return lines;
}

// ---------------------------------------------------------------------------
// Public entry point
// ---------------------------------------------------------------------------

export function exportDesignMd(kit: BrandKit): string {
  return [...buildFrontmatter(kit), ...buildBody(kit)].join('\n');
}
