/**
 * Glossary Exporter
 *
 * Pure function: BrandKit → CONTEXT.md-style glossary string.
 * Emits canonical brand terminology for downstream consumers (writers,
 * agents, validators) so they don't reinvent vocabulary.
 *
 * Designed to be dropped into a project as `CONTEXT.md` or imported
 * by skills like forge-signal's validate-content (Pass 0).
 */

import type { BrandKit } from '../schema/brand-kit.js';

export function exportGlossary(kit: BrandKit): string {
  const lines: string[] = [];
  const { identity, voice, colors, typography } = kit;

  lines.push(`# ${identity.name} — Brand Glossary`);
  lines.push('');
  lines.push(`*Generated from \`brand-kit.json\` (id: \`${kit.meta.id}\`, version: \`${kit.meta.version}\`).*`);
  lines.push('*This is the canonical vocabulary. Update the brand kit to change these terms — do not edit this file directly.*');
  lines.push('');
  lines.push('---');
  lines.push('');

  // --- Identity ---
  lines.push('## Identity terms');
  lines.push('');
  lines.push(`- **${identity.name}** — the brand. Always referred to by this exact name.`);
  if (identity.tagline) lines.push(`- **Tagline** — "${identity.tagline}"`);
  if (identity.mission) lines.push(`- **Mission** — ${identity.mission}`);
  if (identity.positioning) lines.push(`- **Positioning** — ${identity.positioning}`);
  if (identity.audience.length) {
    lines.push(`- **Audience** — ${identity.audience.join('; ')}. Use these segment names, not synonyms.`);
  }
  if (identity.personality.length) {
    lines.push(`- **Personality traits** — ${identity.personality.join(', ')}.`);
  }
  if (identity.domain) lines.push(`- **Domain** — ${identity.domain}`);
  lines.push('');

  // --- Voice attributes ---
  lines.push('## Voice attributes');
  lines.push('');
  lines.push('Each attribute is an enforcement target. Content that does not reflect these traits should be flagged by `validate-content`.');
  lines.push('');
  for (const attr of voice.attributes) {
    lines.push(`- **${attr.trait}** — ${attr.description}`);
    if (attr.example) lines.push(`  - *Example*: "${attr.example}"`);
  }
  lines.push('');

  // --- Anti-patterns (the avoid list) ---
  if (voice.antiPatterns.length) {
    lines.push('## Anti-patterns (do not use)');
    lines.push('');
    lines.push('These patterns violate the brand voice. The `validate-content` skill scans for them in Pass 0.');
    lines.push('');
    for (const ap of voice.antiPatterns) {
      const severity = ap.severity === 'error' ? '**ERROR**' : '*warning*';
      lines.push(`### ${ap.category} (${severity})`);
      for (const p of ap.patterns) {
        lines.push(`- \`${p}\``);
      }
      if (ap.suggestion) lines.push(`- **Instead**: ${ap.suggestion}`);
      lines.push('');
    }
  }

  // --- Structural patterns ---
  if (voice.structuralPatterns.length) {
    lines.push('## Structural patterns');
    lines.push('');
    for (const sp of voice.structuralPatterns) {
      const required = sp.required ? '**required**' : 'optional';
      lines.push(`- **${sp.name}** (${required}) — ${sp.description}`);
      if (sp.example) lines.push(`  - *Example*: ${sp.example}`);
    }
    lines.push('');
  }

  // --- Voice examples ---
  if (voice.examples.length) {
    lines.push('## Voice examples (good vs bad)');
    lines.push('');
    for (const ex of voice.examples) {
      lines.push(`### Intent: ${ex.intent}`);
      lines.push('');
      lines.push(`- ✅ **${kit.identity.name} voice**: ${ex.good}`);
      lines.push(`- ❌ **Off-voice**: ${ex.bad}`);
      lines.push('');
    }
  }

  // --- Color terms ---
  lines.push('## Color terms');
  lines.push('');
  lines.push('Refer to colors by their canonical name, not their hex value.');
  lines.push('');
  lines.push(`- **${colors.primary.name}** (\`${colors.primary.hex}\`) — primary brand color`);
  lines.push(`- **${colors.secondary.name}** (\`${colors.secondary.hex}\`) — secondary`);
  lines.push(`- **${colors.accent.name}** (\`${colors.accent.hex}\`) — accent`);
  lines.push('');

  // --- Typography terms ---
  lines.push('## Typography terms');
  lines.push('');
  lines.push(`- **Display family** — ${typography.display.family}`);
  lines.push(`- **Body family** — ${typography.body.family}`);
  lines.push('');

  // --- Footer ---
  lines.push('---');
  lines.push('');
  lines.push(`*Voice scoring threshold: ${voice.minimumScore}/100. Content scoring below this should be revised before publish.*`);
  lines.push('');
  lines.push(`*Regenerate this file with:* \`brand-forge export glossary --kit ${kit.meta.id}.json\``);
  lines.push('');

  return lines.join('\n');
}
