/**
 * Tailwind Preset Exporter
 *
 * Pure function: BrandKit → Tailwind CSS preset object (as a string).
 * Output is a valid TypeScript file that exports a Tailwind preset.
 *
 * Consumers import this as: `presets: [require('./brand-preset')]`
 * or in Tailwind v4: reference the CSS tokens directly.
 */

import type { BrandKit } from '../schema/brand-kit.js';

export function exportTailwindPreset(kit: BrandKit): string {
  const lines: string[] = [];

  lines.push('/**');
  lines.push(` * ${kit.identity.name} — Tailwind CSS Preset`);
  lines.push(` * Generated by brand-forge v${kit.meta.version}`);
  lines.push(' * DO NOT EDIT — regenerate with: brand-forge export tailwind');
  lines.push(' */');
  lines.push('');
  lines.push('/** @type {import("tailwindcss").Config} */');
  lines.push('export default {');
  lines.push('  theme: {');
  lines.push('    extend: {');

  // --- Colors ---
  lines.push('      colors: {');
  lines.push(`        primary: '${kit.colors.primary.hex}',`);
  lines.push(`        secondary: '${kit.colors.secondary.hex}',`);
  lines.push(`        accent: '${kit.colors.accent.hex}',`);

  // Neutral scale
  lines.push('        neutral: {');
  for (const [step, hex] of Object.entries(kit.colors.neutral)) {
    lines.push(`          '${step}': '${hex}',`);
  }
  lines.push('        },');

  // Semantic
  lines.push(`        success: '${kit.colors.semantic.success.hex}',`);
  lines.push(`        warning: '${kit.colors.semantic.warning.hex}',`);
  lines.push(`        error: '${kit.colors.semantic.error.hex}',`);
  lines.push(`        info: '${kit.colors.semantic.info.hex}',`);

  // Surfaces
  lines.push('        surface: {');
  for (const [name, hex] of Object.entries(kit.colors.surfaces)) {
    const kebab = name.replace(/([A-Z])/g, '-$1').toLowerCase();
    lines.push(`          '${kebab}': '${hex}',`);
  }
  lines.push('        },');
  lines.push('      },');

  // --- Typography ---
  lines.push('      fontFamily: {');
  const { display, body, mono } = kit.typography;
  lines.push(`        display: ['${display.family}', ${display.fallbacks.map((f) => `'${f}'`).join(', ')}],`);
  lines.push(`        body: ['${body.family}', ${body.fallbacks.map((f) => `'${f}'`).join(', ')}],`);
  lines.push(`        mono: ['${mono.family}', ${mono.fallbacks.map((f) => `'${f}'`).join(', ')}],`);
  lines.push('      },');

  // --- Font Size (from type scale) ---
  lines.push('      fontSize: {');
  for (const step of kit.typography.scale.steps) {
    lines.push(`        '${step.name}': ['${step.sizeRem}rem', { lineHeight: '${step.lineHeight}', fontWeight: '${step.weight}' }],`);
  }
  lines.push('      },');

  // --- Spacing ---
  lines.push('      spacing: {');
  for (const [step, rem] of Object.entries(kit.spacing)) {
    lines.push(`        '${step}': '${rem}rem',`);
  }
  lines.push('      },');

  // --- Border Radius ---
  lines.push('      borderRadius: {');
  for (const [name, rem] of Object.entries(kit.radius)) {
    if (name === 'full') {
      lines.push(`        full: '9999px',`);
    } else if (name === 'none') {
      lines.push(`        none: '0',`);
    } else {
      lines.push(`        '${name}': '${rem}rem',`);
    }
  }
  lines.push('      },');

  // --- Breakpoints ---
  lines.push('      screens: {');
  for (const [name, px] of Object.entries(kit.layout.breakpoints)) {
    lines.push(`        '${name}': '${px}px',`);
  }
  lines.push('      },');

  // --- Max Width ---
  lines.push('      maxWidth: {');
  lines.push(`        content: '${kit.layout.maxContentWidth}rem',`);
  lines.push('      },');

  lines.push('    },');
  lines.push('  },');
  lines.push('};');

  return lines.join('\n');
}
